(function() {var implementors = {};
implementors["wrapped2d"] = ["impl <a class='trait' href='https://doc.rust-lang.org/nightly/core/ops/trait.Mul.html' title='core::ops::Mul'>Mul</a>&lt;<a class='primitive' href='https://doc.rust-lang.org/nightly/std/primitive.f32.html'>f32</a>&gt; for <a class='struct' href='wrapped2d/common/math/struct.Vec2.html' title='wrapped2d::common::math::Vec2'>Vec2</a>","impl&lt;'a&gt; <a class='trait' href='https://doc.rust-lang.org/nightly/core/ops/trait.Mul.html' title='core::ops::Mul'>Mul</a>&lt;<a class='primitive' href='https://doc.rust-lang.org/nightly/std/primitive.f32.html'>f32</a>&gt; for &amp;'a <a class='struct' href='wrapped2d/common/math/struct.Vec2.html' title='wrapped2d::common::math::Vec2'>Vec2</a>","impl&lt;'a&gt; <a class='trait' href='https://doc.rust-lang.org/nightly/core/ops/trait.Mul.html' title='core::ops::Mul'>Mul</a>&lt;&amp;'a <a class='primitive' href='https://doc.rust-lang.org/nightly/std/primitive.f32.html'>f32</a>&gt; for <a class='struct' href='wrapped2d/common/math/struct.Vec2.html' title='wrapped2d::common::math::Vec2'>Vec2</a>","impl&lt;'a, 'b&gt; <a class='trait' href='https://doc.rust-lang.org/nightly/core/ops/trait.Mul.html' title='core::ops::Mul'>Mul</a>&lt;&amp;'a <a class='primitive' href='https://doc.rust-lang.org/nightly/std/primitive.f32.html'>f32</a>&gt; for &amp;'b <a class='struct' href='wrapped2d/common/math/struct.Vec2.html' title='wrapped2d::common::math::Vec2'>Vec2</a>","impl&lt;'a&gt; <a class='trait' href='https://doc.rust-lang.org/nightly/core/ops/trait.Mul.html' title='core::ops::Mul'>Mul</a>&lt;<a class='struct' href='wrapped2d/common/math/struct.Vec2.html' title='wrapped2d::common::math::Vec2'>Vec2</a>&gt; for &amp;'a <a class='struct' href='wrapped2d/common/math/struct.Transform.html' title='wrapped2d::common::math::Transform'>Transform</a>",];

            if (window.register_implementors) {
                window.register_implementors(implementors);
            } else {
                window.pending_implementors = implementors;
            }
        
})()
